# Generated by Django 5.1.7 on 2026-03-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_image", models.ImageField(upload_to="inspection_jobs/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("processing_finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("bbox_x_min", models.FloatField()),
                ("bbox_y_min", models.FloatField()),
                ("bbox_x_max", models.FloatField()),
                ("bbox_y_max", models.FloatField()),
                ("estimated_width_mm", models.FloatField(blank=True, null=True)),
                ("estimated_height_mm", models.FloatField(blank=True, null=True)),
                (
                    "estimated_scale_mm_per_pixel",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "size_status",
                    models.CharField(
                        choices=[
                            ("UNDER", "Under"),
                            ("OK", "OK"),
                            ("OVER", "Over"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="inspections.inspectionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
